language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

script:
  - export GO111MODULE="on"
  - go mod download
  - cp store/{config-sample.yml,config.yml}
  - go test

notifications:
  email:
    on_success: change
    on_failure: always
