database:
  driver: "sqlite"
  dbname: "gpass"
  username: "user"
  password: config.Server.Salt
  host: "localhost"
  port: "5432"

server:
  port: "8081"
  username: "gpass"
  password: config.Server.Salt
  