version: '3.3'

services:
  postgres:
    container_name: passwall-postgresql
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=passwall
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/passwall-postgres:/var/lib/postgresql/data
  
