database:
  driver: "sqlite"
  dbname: "passwall"
  username: "user"
  password: "password"

# Uncomment for mysql
# database:
#   driver: "mysql"
#   dbname: "passwall"
#   username: "user"
#   password: "password"
#   host: "localhost" # or compose service name
#   port: "3306"

# Uncomment for postgres
# database:
#   driver: "postgres"
#   dbname: "passwall"
#   username: "user"
#   password: "password"
#   host: "localhost" # or compose service name
#   port: "5432"

server:
  port: "3625"
  username: "passwall"
  password: "password"
  passphrase: "change-me-and-do-not-forget" # required for encrypting passwords
  secret: "JOa{+KBm5:hj]?k1}B2#Fry{C;j[k}-[|-9G:#b]" # required for JWT Token
  timeout: 24 # Token duration in hours format
  generatedPasswordLength: 16 # Minimum 4